export const LOAD_PRODUCTS_REQUEST = "LOAD_PRODUCTS_REQUEST";

export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";

export const SET_LOADING = "SET_LOADING";

export const SET_PRODUCTS = "SET_PRODUCTS";

export const LOAD_PRODUCTS_FAILURE = "LOAD_PRODUCTS_FAILURE";

export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";